name: play_kido
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_widgets: ^1.1.0
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen_runner: ^5.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  lottie: ^3.2.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/poppins/
    - assets/
    - assets/icon/
    - assets/character/
    - assets/letters/
    - assets/sounds/
    - assets/animated_alphabits/
    - assets/audio_alphabet/
    - assets/plain_alphabet/
    - assets/phonics_things/
    - assets/alphabit_audio_sounds/
    - assets/numeric_en/
    - assets/shapes/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/poppins/Poppins-Bold.ttf
          weight: 700
    - family: ComicSans
      fonts:
        - asset: assets/poppins/comic-sans.ttf

flutter_intl:  
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen